### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/PluginAnnotations#3]
I got this err when run this plugin with Murder
Invaild Config.yml. Jar does not contain file config.yml (My english is bad :p)
How to fix this?

 I need this plugin because when I use Murder plugin, with /murderarena finish, it's show up an err, and i know this plugin is needed for Murder plugin

**Comment by InventivetalentDev** [comment]
There's nothing wrong with this plugin, it's just not meant to be installed separately.
